# Generated by Django 5.2 on 2025-04-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie_Assurance',
            fields=[
                ('compagnie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('email_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.URLField(blank=True, help_text="URL de l'API GraphQL de la compagnie d'assurance", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('historique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('information_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_employe', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_assurance', models.CharField(blank=True, max_length=255, null=True)),
                ('cin', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField()),
                ('email_notification', models.EmailField(blank=True, help_text='Email où envoyer la notification pour cette information', max_length=255, null=True)),
                ('compagnie_assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations', to='rh_app.compagnie_assurance')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.CharField(blank=True, max_length=255, null=True)),
                ('expediteur', models.CharField(blank=True, max_length=255, null=True)),
                ('destinataire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.BooleanField(null=True)),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rh_app.historique')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rh_app.information')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='rh_app.utilisateur'),
        ),
    ]
