# Generated by Django 5.2 on 2025-04-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('information_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_employe', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_assurance', models.CharField(blank=True, max_length=255, null=True)),
                ('cin', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('rh_information_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('expediteur', models.CharField(blank=True, max_length=255, null=True)),
                ('destinataire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
                ('rh_notification_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employe_app.information')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('historique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='employe_app.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('rh_utilisateur_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='employe_app.utilisateur'),
        ),
    ]
